### ISSUE TITLE
Fix version of omero-install, or add to ansible, or add regular tests?

### ISSUE THREAD

**Issue by manics** [IDR/jupyter-docker#1]
https://github.com/IDR/jupyter-docker/blob/master/Dockerfile#L5: `RUN git clone git://github.com/ome/omero-install .`
If `omero-install@master` changes it could potentially break this image without use realising.

**Comment by joshmoore** [comment]
+1 for using the v5.2.5 tag: https://github.com/ome/omero-install/releases

cc: @jburel

**Comment by jburel** [comment]
Are we only planning to use it in the context of IDR? (under IDR)
This could be a very useful feature of analysis training in general.

**Comment by joshmoore** [comment]
Not necessarily. Just getting things ready for the paper. If we need to refactor to OME and then re-fork here we can.

**Comment by jburel** [comment]
understood, thanks

**Comment by manics** [comment]
Ideally if it's in the IDR it's "production" and should be converted to Ansible.

**Comment by joshmoore** [comment]
Sounds like a next step.
