### ISSUE TITLE
Get rid of the develop branch

### ISSUE THREAD

**Issue by manics** [IDR/jupyter-docker#15]
Just `master` should be sufficient

**Comment by sbesson** [comment]
As mentioned in https://github.com/IDR/jupyter-docker/pull/13#issuecomment-343902789, this is technically costless as the branches have not diverged and unless there are development incentives to maintaining 2 development branches, I would also vote for trimming it down to `master `only.

**Comment by joshmoore** [comment]
WFM

**Comment by sbesson** [comment]
Fast forwarded `master` to  0fa4445 and deleted the redundant `develop` branch after changing the base branch of #13.
